// Session Actions
export const ACTION_LOGGING_IN_REQUEST = "ACTION_LOGGING_IN_REQUEST";
export const ACTION_LOGGING_IN_REQUEST_SUCCESS = "ACTION_LOGGING_IN_REQUEST_SUCCESS";
export const ACTION_LOGGING_IN_REQUEST_FAILURE = "ACTION_LOGGING_IN_REQUEST_FAILURE";
// Reset password actions
export const ACTION_RESET_PASSWORD_IN_REQUEST = "ACTION_RESET_PASSWORD_IN_REQUEST";
export const ACTION_RESET_PASSWORD_IN_REQUEST_SUCCESS = "ACTION_RESET_PASSWORD_IN_REQUEST_SUCCESS";
export const ACTION_RESET_PASSWORD_IN_REQUEST_FAILURE = "ACTION_RESET_PASSWORD_IN_REQUEST_FAILURE";
// Account verification
export const ACTION_ACCOUNT_VERIFICATION_IN_REQUEST = "ACTION_ACCOUNT_VERIFICATION_IN_REQUEST";
export const ACTION_ACCOUNT_VERIFICATION_SUCCESS = "ACTION_ACCOUNT_VERIFICATION_SUCCESS";
export const ACTION_ACCOUNT_VERIFICATION_FAILURE = "ACTION_ACCOUNT_VERIFICATION_FAILURE";
// Menu
export const ACTION_GET_CLIENT_MENU = "ACTION_GET_CLIENT_MENU";
export const ACTION_GET_CLIENT_MENU_SUCCESS = "ACTION_GET_CLIENT_MENU_SUCCESS";
export const ACTION_GET_CLIENT_MENU_FAILURE = "ACTION_GET_CLIENT_MENU_FAILURE";
// Awards
export const ACTION_GET_CLIENT_AWARDS = "ACTION_GET_CLIENT_AWARDS";
export const ACTION_GET_CLIENT_AWARDS_SUCCESS = "ACTION_GET_CLIENT_AWARDS_SUCCESS";
export const ACTION_GET_CLIENT_AWARDS_FAILURE = "ACTION_GET_CLIENT_AWARDS_FAILURE";
export const ACTION_ADD_CLIENT_AWARD = "ACTION_ADD_CLIENT_AWARD";
export const ACTION_ADD_CLIENT_AWARD_SUCCESS = "ACTION_ADD_CLIENT_AWARD_SUCCESS";
export const ACTION_ADD_CLIENT_AWARD_FAILURE = "ACTION_ADD_CLIENT_AWARD_FAILURE";
export const ACTION_DELETE_CLIENT_AWARD = "ACTION_DELETE_CLIENT_AWARD";
export const ACTION_DELETE_CLIENT_AWARD_SUCCESS = "ACTION_DELETE_CLIENT_AWARD_SUCCESS";
export const ACTION_DELETE_CLIENT_AWARD_FAILURE = "ACTION_DELETE_CLIENT_AWARD_FAILURE";
export const ACTION_UPDATE_CLIENT_AWARD = "ACTION_UPDATE_CLIENT_AWARD";
export const ACTION_UPDATE_CLIENT_AWARD_SUCCESS = "ACTION_UPDATE_CLIENT_AWARD_SUCCESS";
export const ACTION_UPDATE_CLIENT_AWARD_FAILURE = "ACTION_UPDATE_CLIENT_AWARD_FAILURE";
// Score
export const ACTION_ADD_CLIENT_SCORE = "ACTION_ADD_CLIENT_SCORE";
export const ACTION_ADD_CLIENT_SCORE_SUCCESS = "ACTION_ADD_CLIENT_SCORE_SUCCESS";
export const ACTION_ADD_CLIENT_SCORE_FAILURE = "ACTION_ADD_CLIENT_SCORE_FAILURE";
export const ACTION_GET_CLIENT_SCORE = "ACTION_GET_CLIENT_SCORE";
export const ACTION_GET_CLIENT_SCORE_SUCCESS = "ACTION_GET_CLIENT_SCORE_SUCCESS";
export const ACTION_GET_CLIENT_SCORE_FAILURE = "ACTION_GET_CLIENT_SCORE_FAILURE";
export const ACTION_UPDATE_CLIENT_SCORE = "ACTION_UPDATE_CLIENT_SCORE";
export const ACTION_UPDATE_CLIENT_SCORE_SUCCESS = "ACTION_UPDATE_CLIENT_SCORE_SUCCESS";
export const ACTION_UPDATE_CLIENT_SCORE_FAILURE = "ACTION_UPDATE_CLIENT_SCORE_FAILURE";
// User
export const ACTION_GET_USERS_BY_CLIENT = "ACTION_GET_USERS_BY_CLIENT";
export const ACTION_GET_USERS_BY_CLIENT_SUCCESS = "ACTION_GET_USERS_BY_CLIENT_SUCCESS";
export const ACTION_GET_USERS_BY_CLIENT_FAILURE = "ACTION_GET_USERS_BY_CLIENT_FAILURE";
export const ACTION_UPDATE_USER = "ACTION_UPDATE_USER";
export const ACTION_UPDATE_USER_SUCCESS = "ACTION_UPDATE_USER_SUCCESS";
export const ACTION_UPDATE_USER_FAILURE = "ACTION_UPDATE_USER_FAILURE";
// Route
export const ACTION_GET_BUSINESS_ROUTE_BY_CLIENT = "ACTION_GET_BUSINESS_ROUTE_BY_CLIENT";
export const ACTION_GET_BUSINESS_ROUTE_BY_CLIENT_SUCCESS = "ACTION_GET_BUSINESS_ROUTE_BY_CLIENT_SUCCESS";
export const ACTION_GET_BUSINESS_ROUTE_BY_CLIENT_FAILURE = "ACTION_GET_BUSINESS_ROUTE_BY_CLIENT_FAILURE";

export const ACTION_GET_BUSINESS_ROUTE_BY_CLIENT_BY_ID = "ACTION_GET_BUSINESS_ROUTE_BY_CLIENT_BY_ID";
export const ACTION_GET_BUSINESS_ROUTE_BY_CLIENT_BY_ID_SUCCESS = "ACTION_GET_BUSINESS_ROUTE_BY_CLIENT_BY_ID_SUCCESS";
export const ACTION_GET_BUSINESS_ROUTE_BY_CLIENT_BY_ID_FAILURE = "ACTION_GET_BUSINESS_ROUTE_BY_CLIENT_BY_ID_FAILURE";

export const ACTION_DELETE_BUSINESS_ROUTE_BY_CLIENT_BY_ID = "ACTION_DELETE_BUSINESS_ROUTE_BY_CLIENT_BY_ID";
export const ACTION_DELETE_BUSINESS_ROUTE_BY_CLIENT_BY_ID_SUCCESS = "ACTION_DELETE_BUSINESS_ROUTE_BY_CLIENT_BY_ID_SUCCESS";
export const ACTION_DELETE_BUSINESS_ROUTE_BY_CLIENT_BY_ID_FAILURE = "ACTION_DELETE_BUSINESS_ROUTE_BY_CLIENT_BY_ID_FAILURE";

export const ACTION_REMOVE_BUSINESS_RESERVES = "ACTION_REMOVE_BUSINESS_RESERVES";
export const ACTION_REMOVE_BUSINESS_RESERVES_SUCCESS = "ACTION_REMOVE_BUSINESS_RESERVES_SUCCESS";
export const ACTION_REMOVE_BUSINESS_RESERVES_FAILURE = "ACTION_REMOVE_BUSINESS_RESERVES_FAILURE";

export const ACTION_UPDATE_BUSINESS_ROUTE_BY_CLIENT_BY_ID = "ACTION_UPDATE_BUSINESS_ROUTE_BY_CLIENT_BY_ID";
export const ACTION_UPDATE_BUSINESS_ROUTE_BY_CLIENT_BY_ID_SUCCESS = "ACTION_UPDATE_BUSINESS_ROUTE_BY_CLIENT_BY_ID_SUCCESS";
export const ACTION_UPDATE_BUSINESS_ROUTE_BY_CLIENT_BY_ID_FAILURE = "ACTION_UPDATE_BUSINESS_ROUTE_BY_CLIENT_BY_ID_FAILURE";

export const ACTION_ADD_BUSINESS_ROUTE_BY_CLIENT = "ACTION_ADD_BUSINESS_ROUTE_BY_CLIENT";
export const ACTION_ADD_BUSINESS_ROUTE_BY_CLIENT_SUCCESS = "ACTION_ADD_BUSINESS_ROUTE_BY_CLIENT_SUCCESS";
export const ACTION_ADD_BUSINESS_ROUTE_BY_CLIENT_FAILURE = "ACTION_ADD_BUSINESS_ROUTE_BY_CLIENT_FAILURE";
// User route
export const ACTION_GET_USER_ROUTES_BY_CLIENT = "ACTION_GET_USER_ROUTES_BY_CLIENT";
export const ACTION_GET_USER_ROUTES_BY_CLIENT_SUCCESS = "ACTION_GET_USER_ROUTES_BY_CLIENT_SUCCESS";
export const ACTION_GET_USER_ROUTES_BY_CLIENT_FAILURE = "ACTION_GET_USER_ROUTES_BY_CLIENT_FAILURE";
// Transport
export const ACTION_GET_TRANSPORTS = "ACTION_GET_TRANSPORTS";
export const ACTION_GET_TRANSPORTS_SUCCESS = "ACTION_GET_TRANSPORTS_SUCCESS";
export const ACTION_GET_TRANSPORTS_FAILURE = "ACTION_GET_TRANSPORTS_FAILURE";
// Areas
export const ACTION_ADD_CLIENT_AREA = "ACTION_ADD_CLIENT_AREA";
export const ACTION_ADD_CLIENT_AREA_SUCCESS = "ACTION_ADD_CLIENT_AREA_SUCCESS";
export const ACTION_ADD_CLIENT_AREA_FAILURE = "ACTION_ADD_CLIENT_AREA_FAILURE";
export const ACTION_GET_CLIENT_AREA = "ACTION_GET_CLIENT_AREA";
export const ACTION_GET_CLIENT_AREA_SUCCESS = "ACTION_GET_CLIENT_AREA_SUCCESS";
export const ACTION_GET_CLIENT_AREA_FAILURE = "ACTION_GET_CLIENT_AREA_FAILURE";
export const ACTION_DELETE_CLIENT_AREA = "ACTION_DELETE_CLIENT_AREA";
export const ACTION_DELETE_CLIENT_AREA_SUCCESS = "ACTION_DELETE_CLIENT_AREA_SUCCESS";
export const ACTION_DELETE_CLIENT_AREA_FAILURE = "ACTION_DELETE_CLIENT_AREA_FAILURE";
export const ACTION_UPDATE_CLIENT_AREA = "ACTION_UPDATE_CLIENT_AREA";
export const ACTION_UPDATE_CLIENT_AREA_SUCCESS = "ACTION_UPDATE_CLIENT_AREA_SUCCESS";
export const ACTION_UPDATE_CLIENT_AREA_FAILURE = "ACTION_UPDATE_CLIENT_AREA_FAILURE";
// Campaings
export const ACTION_ADD_CLIENT_CAMPAIGN = "ACTION_ADD_CLIENT_CAMPAIGN";
export const ACTION_ADD_CLIENT_CAMPAIGN_SUCCESS = "ACTION_ADD_CLIENT_CAMPAIGN_SUCCESS";
export const ACTION_ADD_CLIENT_CAMPAIGN_FAILURE = "ACTION_ADD_CLIENT_CAMPAIGN_FAILURE";
export const ACTION_GET_CLIENT_CAMPAIGN = "ACTION_GET_CLIENT_CAMPAIGN";
export const ACTION_GET_CLIENT_CAMPAIGN_SUCCESS = "ACTION_GET_CLIENT_CAMPAIGN_SUCCESS";
export const ACTION_GET_CLIENT_CAMPAIGN_FAILURE = "ACTION_GET_CLIENT_CAMPAIGN_FAILURE";
export const ACTION_UPDATE_CLIENT_CAMPAIGN = "ACTION_UPDATE_CLIENT_CAMPAIGN";
export const ACTION_UPDATE_CLIENT_CAMPAIGN_SUCCESS = "ACTION_UPDATE_CLIENT_CAMPAIGN_SUCCESS";
export const ACTION_UPDATE_CLIENT_CAMPAIGN_FAILURE = "ACTION_UPDATE_CLIENT_CAMPAIGN_FAILURE";
// Schedule
export const ACTION_GET_CLIENT_SCHEDULE = "ACTION_GET_CLIENT_SCHEDULE";
export const ACTION_GET_CLIENT_SCHEDULE_SUCCESS = "ACTION_GET_CLIENT_SCHEDULE_SUCCESS";
export const ACTION_GET_CLIENT_SCHEDULE_FAILURE = "ACTION_GET_CLIENT_SCHEDULE_FAILURE";
export const ACTION_UPDATE_CLIENT_SCHEDULE = "ACTION_UPDATE_CLIENT_SCHEDULE";
export const ACTION_UPDATE_CLIENT_SCHEDULE_SUCCESS = "ACTION_UPDATE_CLIENT_SCHEDULE_SUCCESS";
export const ACTION_UPDATE_CLIENT_SCHEDULE_FAILURE = "ACTION_UPDATE_CLIENT_SCHEDULE_FAILURE";
// Offices
export const ACTION_ADD_CLIENT_OFFICE = "ACTION_ADD_CLIENT_OFFICE";
export const ACTION_ADD_CLIENT_OFFICE_SUCCESS = "ACTION_ADD_CLIENT_OFFICE_SUCCESS";
export const ACTION_ADD_CLIENT_OFFICE_FAILURE = "ACTION_ADD_CLIENT_OFFICE_FAILURE";
export const ACTION_GET_CLIENT_OFFICES = "ACTION_GET_CLIENT_OFFICES";
export const ACTION_GET_CLIENT_OFFICES_SUCCESS = "ACTION_GET_CLIENT_OFFICES_SUCCESS";
export const ACTION_GET_CLIENT_OFFICES_FAILURE = "ACTION_GET_CLIENT_OFFICES_FAILURE";
export const ACTION_GET_CLIENT_OFFICE_BY_ID = "ACTION_GET_CLIENT_OFFICE_BY_ID";
export const ACTION_GET_CLIENT_OFFICE_BY_ID_SUCCESS = "ACTION_GET_CLIENT_OFFICE_BY_ID_SUCCESS";
export const ACTION_GET_CLIENT_OFFICE_BY_ID_FAILURE = "ACTION_GET_CLIENT_OFFICE_BY_ID_FAILURE";
export const ACTION_UPDATE_CLIENT_OFFICE = "ACTION_UPDATE_CLIENT_OFFICE";
export const ACTION_UPDATE_CLIENT_OFFICE_SUCCESS = "ACTION_UPDATE_CLIENT_OFFICE_SUCCESS";
export const ACTION_UPDATE_CLIENT_OFFICE_FAILURE = "ACTION_UPDATE_CLIENT_OFFICE_FAILURE";
export const ACTION_DELETE_CLIENT_OFFICE = "ACTION_DELETE_CLIENT_OFFICE";
export const ACTION_DELETE_CLIENT_OFFICE_SUCCESS = "ACTION_DELETE_CLIENT_OFFICE_SUCCESS";
export const ACTION_DELETE_CLIENT_OFFICE_FAILURE = "ACTION_DELETE_CLIENT_OFFICE_FAILURE";
// Client config
export const ACTION_GET_CLIENT_CONFIG = "ACTION_GET_CLIENT_CONFIG";
export const ACTION_GET_CLIENT_CONFIG_SUCCESS = "ACTION_GET_CLIENT_CONFIG_SUCCESS";
export const ACTION_GET_CLIENT_CONFIG_FAILURE = "ACTION_GET_CLIENT_CONFIG_FAILURE";
export const ACTION_UPDATE_CLIENT_CONFIG = "ACTION_UPDATE_CLIENT_CONFIG";
export const ACTION_UPDATE_CLIENT_CONFIG_SUCCESS = "ACTION_UPDATE_CLIENT_CONFIG_SUCCESS";
export const ACTION_UPDATE_CLIENT_CONFIG_FAILURE = "ACTION_UPDATE_CLIENT_CONFIG_FAILURE";

// Snackbar
export const HANDLE_SNACK_BAR = "HANDLE_SNACK_BAR";
